server:
  port: 8081

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: li.jesse.nbaccount.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl         # print sql log