mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl         # print sql log

spring:
  application:
    name: namebook-account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.25.128:5432/namebook
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: postgres
    hikari:
      pool-name: namebook-account-pool
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 8090
